- name: ping test
  hosts: svr
  gather_facts: true
  vars_files:
    - secret.yml #pass_is_same_as_filename
  vars:
    ansible_become_password: "{{ sudo_pass }}"
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  
  tasks:
    - name: role_install
      include_role:
        name: geerlingguy.docker
